### ISSUE TITLE
How to Create an Issue Guide

### ISSUE THREAD

**Issue by nerdnugget** [NODE-Collective/specification#18]
Provide a write up and/or video with how to create "Issues" in Github if people have feedback. This will be the preferred feedback method, both for transparency as well as ensuring that items do not get lost in someone's email/Slack/Google notes etc.

When to create an issue vs. when to start a discussion

**Comment by mpusto** [comment]
Doc is [here](https://docs.google.com/document/d/1viqtmATZYrM5xa6es2j82sCfq-PIFopY0hKbfHGF9To/edit?usp=sharing)

**Comment by mpusto** [comment]
Would love your thoughts @nerdnugget @oyamauchi @FredericoAndrade on where we should put this? Once that's decided I can create a PR for whatever place it belongs.

**Comment by oyamauchi** [comment]
The doc content looks fine to me. I think the content should go in the README, since that's what's shown when someone navigates to the main repo page. We'll also want to create an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) with further guidance on what we want to see in an issue.

**Comment by mpusto** [comment]
Thanks @oyamauchi. I can create a PR for the README, I just set it up in the Discussions section but README is good too. I [created an Issue Template and am waiting on PR approval](https://github.com/NODE-Collective/specification/pull/21) from @FredericoAndrade, although you are welcome to approve as well.
